
name: apixis build2

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: 'Project Name'
        required: true
      pathName:
        description: 'Path Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspi_4_bookworm:20231109
        commands: ./test.sh
