name: Build Project

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: 'Project Name'
        required: true
      projectBranch:
        description: 'Project Branch'
        required: true
      jdkVersion:
        description: 'Jdk Version'
        required: true
      nodeVersion:
        description: 'Node Version'
        required: true
      mvnCommand:
        description: 'build Command'
        required: true
      pathName:
        description: 'Path Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: '${{ github.event.inputs.projectName }}'
        ref: '${{ github.event.inputs.projectBranch }}'

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '${{ github.event.inputs.jdkVersion }}'
        distribution: 'adopt'

    - name: Build with Maven
      run: ${{ github.event.inputs.mvnCommand }}

    - name: Compress the TAR files
      run: tar -czf project-package.tar.gz ${{ github.event.inputs.pathName }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: project-package
        path: project-package.tar.gz
        retention-days: 1
