
name: test-command
 
on:
  workflow_dispatch
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: test-command
      run: |
        docker info
        docker version
        docker compose version
        lscpu
        free -m
        df -h /
