
name: test-command
 
on:
  workflow_dispatch:
    inputs:
      projectName:
        description: 'anyting'
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: test-command
      run: |
        docker info
        docker version
        docker compose version
